version: "3"

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:14.0
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: superadmin
      POSTGRES_DB: blogDB
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - app-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: blog-app
    command: yarn start:dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: on-failure
    networks:
      - app-network
    env_file:
      - .env

volumes:
  plagiarism:

